title: Genie Press
email: sunil@lnk7.com
description: "Build awesome (Laravelesque) WordPress Plugins and Themes "
baseurl: ""
url: ""
twitter_username:
github_username: lnk7
theme: "just-the-docs"
plugins:
  - jekyll-feed

permalink: pretty

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

heading_anchors: true
